image: node:latest

pages:
  stage: deploy
  environment:
    name: frontend
    url: '$CI_PAGES_URL'
  script:
    - mkdir .public
    - cp index.html .public/
    - cp toggler.js .public/
    - cp toggler.css .public/
  artifacts:
    paths:
      - .public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
