default:
  image: node:latest

pages:
  stage: deploy
  only:
    refs:
      - main
  environment:
    name: frontend
    url: '$CI_PAGES_URL'
  script:
    - mkdir .public
    - cp index.html .public/
    - cp toggler.js .public/
    - cp toggler.css .public/
    - mv .public public
  artifacts:
    paths:
      - public

